name: NextNeko
version: 1.1.0-beta
authors: [_Chinese_Player_]
description: 一个融合了NekoC和toNeko功能的猫娘插件
main: org.cneko.nekox.NextNeko
api-version: 1.13

commands:
  pat:
    description: 抚摸猫娘
    usage: /<command> <玩家>
    permission: nextneko.pat
  lovebite:
    description: 给玩家一个爱的咬痕（猫娘使用）
    usage: /<command> <玩家>
    permission: nextneko.lovebite
  earscratch:
    description: 挠猫娘的耳朵
    usage: /<command> <玩家>
    permission: nextneko.earscratch
  purr:
    description: 发出呼噜声（猫娘使用）
    usage: /<command>
    permission: nextneko.purr
  hiss:
    description: 发出嘶嘶声（猫娘使用）
    usage: /<command> <玩家>
    permission: nextneko.hiss
  scratch:
    description: 挠人（猫娘使用）
    usage: /<command> <玩家>
    permission: nextneko.scratch
  attention:
    description: 吸引人类的注意（猫娘使用）
    usage: /<command> <玩家>
    permission: nextneko.attention
  nightvision:
    description: 获得夜视效果（猫娘使用）
    usage: /<command> [玩家]
    permission: nextneko.nightvision
  jumpboost:
    description: 获得跳跃提升效果（猫娘使用）
    usage: /<command> [玩家]
    permission: nextneko.jumpboost
  swiftsneak:
    description: 获得迅捷潜行效果（猫娘使用）
    usage: /<command> [玩家]
    permission: nextneko.swiftsneak
  health:
    description: 恢复自己和主人的生命值（猫娘使用）
    usage: /<command>
    permission: nextneko.health
  myskills:
    description: 查看猫娘的所有技能及其冷却时间
    usage: /<command>
    permission: nextneko.myskills
  nextneko:
    description: NextNeko主命令
    usage: /<command> <reload/version>
    permission: nextneko.admin
  nextnekohelp:
    description: 查看NextNeko帮助信息
    usage: /<command>
    permission: nextneko.help
  nekoset:
    description: 设置/取消设置玩家为猫娘
    usage: /<command> <玩家> <true/false>
    permission: nextneko.admin
  owner:
    description: 主人系统命令
    usage: /<command> <add/remove/list/mylist/help> [玩家]
    permission: nextneko.owner
  playernotice:
    description: 开启/关闭玩家接近提醒功能（猫娘使用）
    usage: /<command> [on|off]
    permission: nextneko.playernotice
  climb:  # 添加爬墙命令
    description: 开启/关闭爬墙功能（猫娘使用）
    usage: /<command>
    permission: nextneko.climb
  pullthetail:
    description: 开启/关闭尾巴拉扯功能
    usage: /<command>
    permission: nextneko.pullthetail

permissions:
  nextneko.pat:
    default: true
  nextneko.lovebite:
    default: true
  nextneko.earscratch:
    default: true
  nextneko.purr:
    default: true
  nextneko.hiss:
    default: true
  nextneko.scratch:
    default: true
  nextneko.attention:
    default: true
  nextneko.nightvision:
    default: true
  nextneko.jumpboost:
    default: true
  nextneko.swiftsneak:
    default: true
  nextneko.health:
    default: true
  nextneko.help:
    default: true
  nextneko.myskills:
    default: true
  nextneko.playernotice:
    default: true
  nextneko.climb:  # 添加爬墙权限
    default: true
  nextneko.pullthetail:
    default: true
  nextneko.admin:
    default: op
    children:
      nextneko.help: true
  nextneko.owner:
    default: true